export default [
  {
    id: "6",
    name: "Convertir cotizaci\u00f3n a factura",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
  {
    id: "8",
    name: "Tarea de capacitación",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
  {
    id: "1",
    name: "Enviarle el contrato y este es demo",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
  {
    "id": "9",
    "name": "prueba de nueva tarea",
    "description": "",
    "priority": "2",
    "dateadded": "2020-04-13 12:02:31",
    "startdate": "2020-04-13",
    "duedate": null,
    "datefinished": "2020-04-18 12:01:23",
    "addedfrom": "3",
    "is_added_from_contact": "0",
    "status": "5",
    "recurring_type": null,
    "repeat_every": "0",
    "recurring": "0",
    "is_recurring_from": null,
    "cycles": "0",
    "total_cycles": "0",
    "custom_recurring": "0",
    "last_recurring_date": null,
    "rel_id": "5",
    "rel_type": "project",
    "is_public": "0",
    "billable": "1",
    "billed": "0",
    "invoice_id": "0",
    "hourly_rate": "0.00",
    "milestone": "0",
    "kanban_order": "0",
    "milestone_order": "0",
    "visible_to_client": "1",
    "deadline_notified": "0",
    "comments": [],
    "assignees": [
        {
            "id": "9",
            "assigneeid": "3",
            "assigned_from": "3",
            "firstname": "Omar",
            "lastname": "PO",
            "full_name": "Omar PO",
            "is_assigned_from_contact": "0"
        }
    ],
    "assignees_ids": [
        "3"
    ],
    "followers": [],
    "followers_ids": [],
    "attachments": [],
    "timesheets": [],
    "checklist_items": [],
    "milestone_name": "",
    "project_data": {
        "id": "5",
        "name": "Proyecto de manuel",
        "description": "",
        "status": "2",
        "clientid": "13",
        "billing_type": "2",
        "start_date": "2020-04-02",
        "deadline": "2020-04-30",
        "project_created": "2020-04-02",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "100.00",
        "estimated_hours": "100.00",
        "addedfrom": "3",
        "shared_vault_entries": [],
        "project_history_date": [],
        "project_history_expense": [],
        "settings": {
            "available_features": "a:14:{s:16:\"project_overview\";i:1;s:13:\"project_tasks\";i:1;s:18:\"project_timesheets\";i:1;s:18:\"project_milestones\";i:1;s:13:\"project_files\";i:1;s:19:\"project_discussions\";i:1;s:13:\"project_gantt\";i:1;s:15:\"project_tickets\";i:1;s:16:\"project_invoices\";i:1;s:17:\"project_estimates\";i:1;s:16:\"project_expenses\";i:1;s:20:\"project_credit_notes\";i:1;s:13:\"project_notes\";i:1;s:16:\"project_activity\";i:1;}",
            "view_tasks": "1",
            "create_tasks": "1",
            "edit_tasks": "1",
            "comment_on_tasks": "1",
            "view_task_comments": "1",
            "view_task_attachments": "1",
            "view_task_checklist_items": "1",
            "upload_on_tasks": "1",
            "view_task_total_logged_time": "1",
            "view_finance_overview": "1",
            "upload_files": "1",
            "open_discussions": "1",
            "view_milestones": "1",
            "view_gantt": "1",
            "view_timesheets": "1",
            "view_activity_log": "1",
            "view_team_members": "1",
            "hide_tasks_on_main_tasks_table": "0"
        },
        "client_data": {
            "userid": "13",
            "company": "Manuel Ram SA de CV",
            "vat": null,
            "phonenumber": "3344556677",
            "country": "142",
            "city": "Guadalajara",
            "zip": "12391",
            "state": "Jalisco",
            "address": "Calle Negro",
            "website": "",
            "datecreated": "2020-04-02 12:28:22",
            "active": "1",
            "leadid": "27",
            "billing_street": "Calle Negro",
            "billing_city": "Guadalajara",
            "billing_state": "Jalisco",
            "billing_zip": "12391",
            "billing_country": "142",
            "shipping_street": null,
            "shipping_city": null,
            "shipping_state": null,
            "shipping_zip": null,
            "shipping_country": "0",
            "longitude": null,
            "latitude": null,
            "default_language": "",
            "default_currency": "0",
            "show_primary_contact": "0",
            "stripe_id": null,
            "registration_confirmed": "1",
            "addedfrom": "3"
        }
    }
}
,
{
    "id": "10",
    "name": "REQS",
    "description": "",
    "priority": "2",
    "dateadded": "2020-04-13 12:02:35",
    "startdate": "2020-04-13",
    "duedate": null,
    "datefinished": null,
    "addedfrom": "1",
    "is_added_from_contact": "0",
    "status": "4",
    "recurring_type": null,
    "repeat_every": "0",
    "recurring": "0",
    "is_recurring_from": null,
    "cycles": "0",
    "total_cycles": "0",
    "custom_recurring": "0",
    "last_recurring_date": null,
    "rel_id": "5",
    "rel_type": "project",
    "is_public": "0",
    "billable": "1",
    "billed": "0",
    "invoice_id": "0",
    "hourly_rate": "0.00",
    "milestone": "0",
    "kanban_order": "0",
    "milestone_order": "0",
    "visible_to_client": "1",
    "deadline_notified": "0",
    "comments": [],
    "assignees": [],
    "assignees_ids": [],
    "followers": [],
    "followers_ids": [],
    "attachments": [],
    "timesheets": [],
    "checklist_items": [],
    "milestone_name": "",
    "project_data": {
        "id": "5",
        "name": "Proyecto de manuel",
        "description": "",
        "status": "2",
        "clientid": "13",
        "billing_type": "2",
        "start_date": "2020-04-02",
        "deadline": "2020-04-30",
        "project_created": "2020-04-02",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "100.00",
        "estimated_hours": "100.00",
        "addedfrom": "3",
        "shared_vault_entries": [],
        "project_history_date": [],
        "project_history_expense": [],
        "settings": {
            "available_features": "a:14:{s:16:\"project_overview\";i:1;s:13:\"project_tasks\";i:1;s:18:\"project_timesheets\";i:1;s:18:\"project_milestones\";i:1;s:13:\"project_files\";i:1;s:19:\"project_discussions\";i:1;s:13:\"project_gantt\";i:1;s:15:\"project_tickets\";i:1;s:16:\"project_invoices\";i:1;s:17:\"project_estimates\";i:1;s:16:\"project_expenses\";i:1;s:20:\"project_credit_notes\";i:1;s:13:\"project_notes\";i:1;s:16:\"project_activity\";i:1;}",
            "view_tasks": "1",
            "create_tasks": "1",
            "edit_tasks": "1",
            "comment_on_tasks": "1",
            "view_task_comments": "1",
            "view_task_attachments": "1",
            "view_task_checklist_items": "1",
            "upload_on_tasks": "1",
            "view_task_total_logged_time": "1",
            "view_finance_overview": "1",
            "upload_files": "1",
            "open_discussions": "1",
            "view_milestones": "1",
            "view_gantt": "1",
            "view_timesheets": "1",
            "view_activity_log": "1",
            "view_team_members": "1",
            "hide_tasks_on_main_tasks_table": "0"
        },
        "client_data": {
            "userid": "13",
            "company": "Manuel Ram SA de CV",
            "vat": null,
            "phonenumber": "3344556677",
            "country": "142",
            "city": "Guadalajara",
            "zip": "12391",
            "state": "Jalisco",
            "address": "Calle Negro",
            "website": "",
            "datecreated": "2020-04-02 12:28:22",
            "active": "1",
            "leadid": "27",
            "billing_street": "Calle Negro",
            "billing_city": "Guadalajara",
            "billing_state": "Jalisco",
            "billing_zip": "12391",
            "billing_country": "142",
            "shipping_street": null,
            "shipping_city": null,
            "shipping_state": null,
            "shipping_zip": null,
            "shipping_country": "0",
            "longitude": null,
            "latitude": null,
            "default_language": "",
            "default_currency": "0",
            "show_primary_contact": "0",
            "stripe_id": null,
            "registration_confirmed": "1",
            "addedfrom": "3"
        }
    }
},
{
    "id": "11",
    "name": "volcan tarea 1",
    "description": "",
    "priority": "2",
    "dateadded": "2020-04-13 12:40:53",
    "startdate": "2020-04-13",
    "duedate": null,
    "datefinished": "2020-04-13 12:56:31",
    "addedfrom": "3",
    "is_added_from_contact": "0",
    "status": "5",
    "recurring_type": null,
    "repeat_every": "0",
    "recurring": "0",
    "is_recurring_from": null,
    "cycles": "0",
    "total_cycles": "0",
    "custom_recurring": "0",
    "last_recurring_date": null,
    "rel_id": "5",
    "rel_type": "project",
    "is_public": "0",
    "billable": "1",
    "billed": "0",
    "invoice_id": "0",
    "hourly_rate": "0.00",
    "milestone": "0",
    "kanban_order": "0",
    "milestone_order": "0",
    "visible_to_client": "1",
    "deadline_notified": "0",
    "comments": [],
    "assignees": [
        {
            "id": "10",
            "assigneeid": "3",
            "assigned_from": "3",
            "firstname": "Omar",
            "lastname": "PO",
            "full_name": "Omar PO",
            "is_assigned_from_contact": "0"
        }
    ],
    "assignees_ids": [
        "3"
    ],
    "followers": [],
    "followers_ids": [],
    "attachments": [],
    "timesheets": [],
    "checklist_items": [],
    "milestone_name": "",
    "project_data": {
        "id": "6",
        "name": "Volcán Ajusco",
        "description": "",
        "status": "2",
        "clientid": "4",
        "billing_type": "2",
        "start_date": "2020-04-13",
        "deadline": null,
        "project_created": "2020-04-13",
        "date_finished": null,
        "progress": "0",
        "progress_from_tasks": "1",
        "project_cost": "0.00",
        "project_rate_per_hour": "0.00",
        "estimated_hours": "100.00",
        "addedfrom": "3",
        "shared_vault_entries": [],
        "project_history_date": [],
        "project_history_expense": [],
        "settings": {
            "available_features": "a:14:{s:16:\"project_overview\";i:1;s:13:\"project_tasks\";i:1;s:18:\"project_timesheets\";i:1;s:18:\"project_milestones\";i:1;s:13:\"project_files\";i:1;s:19:\"project_discussions\";i:1;s:13:\"project_gantt\";i:1;s:15:\"project_tickets\";i:1;s:16:\"project_invoices\";i:1;s:17:\"project_estimates\";i:1;s:16:\"project_expenses\";i:1;s:20:\"project_credit_notes\";i:1;s:13:\"project_notes\";i:1;s:16:\"project_activity\";i:1;}",
            "view_tasks": "1",
            "create_tasks": "1",
            "edit_tasks": "1",
            "comment_on_tasks": "1",
            "view_task_comments": "1",
            "view_task_attachments": "1",
            "view_task_checklist_items": "1",
            "upload_on_tasks": "1",
            "view_task_total_logged_time": "1",
            "view_finance_overview": "1",
            "upload_files": "1",
            "open_discussions": "1",
            "view_milestones": "1",
            "view_gantt": "1",
            "view_timesheets": "1",
            "view_activity_log": "1",
            "view_team_members": "1",
            "hide_tasks_on_main_tasks_table": "0"
        },
        "client_data": {
            "userid": "4",
            "company": "Monitores S.A.",
            "vat": "",
            "phonenumber": "3327928322",
            "country": "142",
            "city": "",
            "zip": "45070",
            "state": "Jalisco",
            "address": "Matute Remus 1520",
            "website": "",
            "datecreated": "2020-02-14 11:49:58",
            "active": "1",
            "leadid": null,
            "billing_street": "",
            "billing_city": "",
            "billing_state": "",
            "billing_zip": "",
            "billing_country": "0",
            "shipping_street": "",
            "shipping_city": "",
            "shipping_state": "",
            "shipping_zip": "",
            "shipping_country": "0",
            "longitude": null,
            "latitude": null,
            "default_language": null,
            "default_currency": "3",
            "show_primary_contact": "0",
            "stripe_id": null,
            "registration_confirmed": "1",
            "addedfrom": "3"
        }
    }
}
];
