export default [
  {
    id: "6",
    name: "Convertir cotizaci\u00f3n a factura",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
  {
    id: "8",
    name: "Tarea de capacitación",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
  {
    id: "1",
    name: "Enviarle el contrato y este es demo",
    description: "",
    priority: "3",
    dateadded: "2020-02-19 11:07:09",
    startdate: "2020-02-19",
    duedate: "2020-02-20",
    datefinished: null,
    addedfrom: "3",
    is_added_from_contact: "0",
    status: "4",
    recurring_type: null,
    repeat_every: "0",
    recurring: "0",
    is_recurring_from: null,
    cycles: "0",
    total_cycles: "0",
    custom_recurring: "0",
    last_recurring_date: null,
    rel_id: "3",
    rel_type: "estimate",
    is_public: "0",
    billable: "1",
    billed: "0",
    invoice_id: "0",
    hourly_rate: "0.00",
    milestone: "0",
    kanban_order: "0",
    milestone_order: "0",
    visible_to_client: "0",
    deadline_notified: "0",
    comments: [],
    assignees: [
      {
        id: "5",
        assigneeid: "3",
        assigned_from: "3",
        firstname: "Omar",
        lastname: "PO",
        full_name: "Omar PO",
        is_assigned_from_contact: "0",
      },
    ],
    assignees_ids: ["3"],
    followers: [],
    followers_ids: [],
    attachments: [],
    timesheets: [],
    checklist_items: [],
    milestone_name: "",
  },
];
